version: "3.8"
services:
  web:
    build: .
    environment:
      - OTEL_LOG_LEVEL=info
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp

      - LOG_LEVEL=debug

      - OTEL_SERVICE_NAME=demo-app-node-otlp

      - PORT=8081
    ports:
      - "8081:8081"
    networks:
      - observability

networks:
  observability:
    name: observability
    external: true
